import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { formatStamina } from '../format.js';
import { useLocale } from '../i18n/Locale.js';
import { NAV_ASSET_ICON, NAV_ICON, NAV_UI_ICON, assetUrl, uiUrl } from '../ui/chrome.js';
import './ObjectiveTracker.css';

export type OverlayId='none'|'helper'|'cyclopedia'|'market'|'loja'|'vip'|'rank'|'build'|'progressao'|'roleta'|'depot'|'guild';
export const NAV:Array<{id:OverlayId;label:string;tone:string}>=[{id:'guild',label:'Guild',tone:'#466a47'},{id:'helper',label:'Helper',tone:'#1e40af'},{id:'cyclopedia',label:'Cyclopedia',tone:'#1d4ed8'},{id:'market',label:'Mercado',tone:'#a16207'},{id:'loja',label:'Loja',tone:'#c2410c'},{id:'vip',label:'VIP',tone:'#b45309'},{id:'rank',label:'Rank',tone:'#7c2d12'},{id:'build',label:'Build',tone:'#3b82f6'},{id:'progressao',label:'Progressão',tone:'#6366f1'},{id:'roleta',label:'Roleta',tone:'#6d28d9'},{id:'depot',label:'Depot',tone:'#92400e'}];
const NAV_UNLOCK:Partial<Record<OverlayId,number>>={helper:1,vip:1,build:8,depot:8,cyclopedia:10,progressao:15,market:20,rank:20,loja:20,roleta:25,guild:30};

const UNLOCK_COPY:Partial<Record<OverlayId,{summary:string;purpose:string}>>={
  helper:{summary:'Assistente para automatizar decisões básicas de combate e sobrevivência.',purpose:'Configurar cura, suprimentos e comportamentos automáticos do personagem.'},
  build:{summary:'Painel para entender e organizar a construção do personagem.',purpose:'Comparar atributos, equipamentos e escolhas que aumentam seu desempenho.'},
  depot:{summary:'Seu espaço seguro para guardar itens fora da mochila.',purpose:'Armazenar equipamentos e loot para liberar espaço no inventário.'},
  cyclopedia:{summary:'Enciclopédia de criaturas e progresso de caça do personagem.',purpose:'Consultar monstros, acompanhar Bestiary e visualizar sua evolução contra cada criatura.'},
  progressao:{summary:'Central dos sistemas avançados de evolução.',purpose:'Reunir recursos como Prey, Imbuements, Forge, Wheel e outras formas de fortalecer o personagem.'},
  market:{summary:'Mercado entre jogadores para itens e recursos.',purpose:'Comprar e vender itens usando a economia do servidor.'},
  rank:{summary:'Classificação dos jogadores e personagens do servidor.',purpose:'Comparar seu progresso com outros jogadores e acompanhar posições no ranking.'},
  loja:{summary:'Área de cosméticos, serviços e conveniências da conta.',purpose:'Acessar itens visuais, serviços e opções de suporte à conta disponíveis na loja.'},
  vip:{summary:'Painel dos benefícios Premium da conta.',purpose:'Consultar e ativar vantagens de conveniência e progressão previstas para o VIP.'},
  roleta:{summary:'Sistema de recompensas extras ligado à progressão.',purpose:'Participar da roleta quando disponível e receber recompensas conforme suas regras.'},
  guild:{summary:'Sistema social para formar uma comunidade dentro do servidor.',purpose:'Criar ou participar de guildas e organizar jogadores em um grupo permanente.'},
};

const TRACKER_HIDDEN_KEY='knock:objective-tracker:hidden';
const TRACKER_MINIMIZED_KEY='knock:objective-tracker:minimized';
function storedFlag(key:string){return typeof window!=='undefined'&&window.localStorage.getItem(key)==='1'}

function Glyph({id}:{id:OverlayId}){switch(id){case'guild':return <g shapeRendering="crispEdges"><path d="M3 2h18v12h-2v4h-3v3h-3v2h-2v-2H8v-3H5v-4H3Z" fill="#091510"/><path d="M4 3h16v10h-2v4h-3v3h-3v1h-1v-2H8v-3H6v-4H4Z" fill="#917132"/><path d="M4 3h16v2H6v8H4Zm2 10h2v3H6Zm2 3h3v3H8Z" fill="#f5df8b"/><path d="M7 6h10v7h-2v3h-3v2h-1v-2H9v-3H7Z" fill="#205540"/><path d="M7 6h5v10H9v-3H7Z" fill="#409c66"/><path d="M12 6h5v7h-2v3h-3Z" fill="#163f34"/><path d="M11 7h2v2h3v2h-2v3h-1v-1h-2v1h-1v-3H8V9h3Z" fill="#d6ad45"/><path d="M11 7h2v2h-2Zm-3 2h5v2H8Z" fill="#fff0ac"/><path d="M5 4h2v2H5Zm12 0h2v2h-2Z" fill="#fff4bf"/></g>;case'helper':return <path d="M10 3c-2 0-3 1.6-3 3.4 0 2.6 3 6.6 5 8.6 2-2 5-6 5-8.6C17 4.6 16 3 14 3c-1.2 0-2 .7-2 1.6C12 3.7 11.2 3 10 3z"/>;case'cyclopedia':return <path d="M5 4h6a3 3 0 0 1 3 3v11H8a3 3 0 0 0-3 3V4zm8 0h2a3 3 0 0 1 3 3v11h-5V7a3 3 0 0 0-3-3z"/>;case'market':return <path d="M6 4h8l4 4v12H6V4zm8 0v4h4"/>;case'loja':return <path d="M4 8h16l-1 12H5L4 8zm3-3h10l1 3H6l1-3z"/>;case'vip':return <path d="M4 8l3 2 5-6 5 6 3-2-2 12H6L4 8z"/>;case'rank':return <path d="M6 16h3V8H6v8zm5 4h3V4h-3v16zm5-7h3V9h-3v4z"/>;case'build':return <path d="M12 3l8 4.5v9L12 21l-8-4.5v-9L12 3z"/>;case'progressao':return <><path d="M4 18V6l8-3 8 3v12l-8 3-8-3z"/><path d="M12 8v8M8 10l4-2 4 2"/></>;case'roleta':return <><circle cx="12" cy="12" r="8"/><path d="M12 5v7l5 3"/></>;case'depot':return <path d="M5 8h14v10a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V8zm2-3h10l1 3H6l1-3z"/>;default:return <circle cx="12" cy="12" r="6"/>}}
function NavIcon({id,tone,badge}:{id:OverlayId;tone:string;badge?:string}){return <span className="ico" style={{background:tone}}>{NAV_ASSET_ICON[id]?<img className="nav-item-icon" src={assetUrl(NAV_ASSET_ICON[id]!)} alt=""/>:NAV_UI_ICON[id]?<img className="nav-ui-icon" src={uiUrl(NAV_UI_ICON[id]!)} alt=""/>:NAV_ICON[id]?<img className="nav-ui-icon" src={uiUrl(NAV_ICON[id]!)} alt=""/>:<svg viewBox="0 0 24 24"><Glyph id={id}/></svg>}{badge!==undefined&&<em>{badge}</em>}</span>}
function MobileMainIcon({id}:{id:'city'|'hunts'|'training'|'menu'}){if(id==='city')return <svg className="mobile-nav-pixel" viewBox="0 0 32 32" aria-hidden="true" shapeRendering="crispEdges"><path fill="#2b1a0b" d="M5 10h5V5h4v5h4V5h4v5h5v17H5z"/><path fill="#b9842b" d="M7 12h4V8h2v4h6V8h2v4h4v13H7z"/><path fill="#e3bd58" d="M9 14h14v3H9zm0 5h4v4H9zm10 0h4v4h-4z"/><path fill="#6a4319" d="M14 18h4v7h-4z"/></svg>;
if(id==='hunts')return <svg className="mobile-nav-pixel" viewBox="0 0 32 32" aria-hidden="true" shapeRendering="crispEdges"><path fill="#4a210e" d="M5 5h4l18 18v4h-4L5 9z"/><path fill="#d9dce2" d="M7 6h3l16 16-4 4L6 10z"/><path fill="#7a8492" d="M17 19l3-3 6 6-3 3z"/><path fill="#8e2b22" d="M23 5h4v4h-2v2h-2v-2h-2V7h2z"/><path fill="#f1c74c" d="M4 22h3v3h3v3H7v-2H4z"/></svg>;
if(id==='training')return <svg className="mobile-nav-pixel" viewBox="0 0 32 32" aria-hidden="true" shapeRendering="crispEdges"><path fill="#28170d" d="M14 2h4v4h4v3h3v4h3v8h-3v4h-3v3H10v-3H7v-4H4v-8h3V9h3V6h4z"/><path fill="#9b2f25" d="M11 7h10v3h3v4h2v6h-2v4h-3v2H11v-2H8v-4H6v-6h2v-4h3z"/><path fill="#e2c38a" d="M12 10h8v2h3v3h2v4h-2v3h-3v2h-8v-2H9v-3H7v-4h2v-3h3z"/><path fill="#b3382c" d="M13 12h6v2h3v3h1v2h-1v2h-3v2h-6v-2h-3v-2H9v-2h1v-3h3z"/><path fill="#f0d79d" d="M14 14h4v2h2v4h-2v2h-4v-2h-2v-4h2z"/><path fill="#5b1b16" d="M15 16h3v4h-3z"/><path fill="#6f4a24" d="M15 26h3v4h-3z"/><path fill="#c89b48" d="M26 4h3v3h-2v2h-2V7h-2V6h3z"/><path fill="#d9dce2" d="M19 12h2v2h-2zm2-2h2v2h-2zm2-2h2v2h-2z"/></svg>;
return <svg className="mobile-nav-pixel" viewBox="0 0 32 32" aria-hidden="true" shapeRendering="crispEdges"><path fill="#563616" d="M6 5h20v22H6z"/><path fill="#c99b45" d="M8 7h16v18H8z"/><path fill="#ead07a" d="M10 9h12v3H10zm0 5h12v3H10zm0 5h8v3h-8z"/><path fill="#352313" d="M22 7h2v18h-2z"/></svg>}

export function TopNav({name,gold,coins,health,maxHealth,mana,maxMana,level,xpPercent,stamina,overlay,onOverlay,onBack,onSettings,onCity,onTraining,badges}:{name:string;gold:number;coins:number;health:number;maxHealth:number;mana:number;maxMana:number;level:number;xpPercent:number;stamina:number;overlay:OverlayId;onOverlay:(id:OverlayId)=>void;onBack:()=>void;onSettings?:()=>void;onCity:()=>void;onTraining:()=>void;badges?:Partial<Record<OverlayId,string>>}){
 const{locale,setLocale,t}=useLocale();
 const[mobileMenu,setMobileMenu]=useState(false);
 const[arenaHead,setArenaHead]=useState<HTMLElement|null>(null);
 const[trackerVisible,setTrackerVisible]=useState(()=>!storedFlag(TRACKER_HIDDEN_KEY));
 const[trackerMinimized,setTrackerMinimized]=useState(()=>storedFlag(TRACKER_MINIMIZED_KEY));
 const hp=Math.max(0,Math.min(100,health/Math.max(1,maxHealth)*100));
 const mp=Math.max(0,Math.min(100,mana/Math.max(1,maxMana)*100));
 const sta=Math.max(0,Math.min(100,stamina/2520*100));
 const levelGoal=Math.max(0,Math.min(100,Math.round(xpPercent)));
 const openMobile=(id:OverlayId)=>{setMobileMenu(false);onOverlay(id)};
 const openHunts=()=>{const picker=document.querySelector('.hunt-pick') as HTMLButtonElement|null;picker?.click();window.setTimeout(()=>{(document.querySelector('[data-tab="hunts"]') as HTMLButtonElement|null)?.click();},0)};
 const visibleNav=NAV.filter(item=>level>=(NAV_UNLOCK[item.id]??1));
 const futureUnlocks=NAV.map(item=>({item,level:NAV_UNLOCK[item.id]??1})).filter(entry=>entry.level>level).sort((a,b)=>a.level-b.level);
 const nextUnlockLevel=futureUnlocks[0]?.level;
 const nextUnlocks=nextUnlockLevel===undefined?[]:futureUnlocks.filter(entry=>entry.level===nextUnlockLevel);
 const laterUnlocks=futureUnlocks.filter(entry=>nextUnlockLevel!==undefined&&entry.level>nextUnlockLevel).slice(0,4);
 const trackerTitle=nextUnlockLevel===undefined?'Sistemas principais liberados':nextUnlocks.length>1?`${nextUnlocks.length} sistemas no nível ${nextUnlockLevel}`:`${nextUnlocks[0]?.item.label} no nível ${nextUnlockLevel}`;
 const hideTracker=()=>{setTrackerVisible(false);if(typeof window!=='undefined')window.localStorage.setItem(TRACKER_HIDDEN_KEY,'1')};
 const showTracker=()=>{setTrackerVisible(true);if(typeof window!=='undefined')window.localStorage.removeItem(TRACKER_HIDDEN_KEY)};
 const toggleTracker=()=>{if(trackerVisible)hideTracker();else{showTracker();setTrackerMinimized(false);if(typeof window!=='undefined')window.localStorage.removeItem(TRACKER_MINIMIZED_KEY)}};
 const toggleTrackerMinimized=()=>setTrackerMinimized(current=>{const next=!current;if(typeof window!=='undefined'){if(next)window.localStorage.setItem(TRACKER_MINIMIZED_KEY,'1');else window.localStorage.removeItem(TRACKER_MINIMIZED_KEY)}return next});

 useEffect(()=>{
  setArenaHead(document.querySelector('.arena-head') as HTMLElement|null);
 },[]);

 return <>
  <header className="topnav"><div className="logo">KNOCK <span>HUNT BR</span></div><div className="who"><strong>{name}</strong><small>lvl {level}</small></div><div className="top-vitals" data-tutorial="vitals"><div className="top-bar"><span>HP</span><div className="meter hp"><i style={{width:`${hp}%`}}/></div></div><div className="top-bar"><span>MP</span><div className="meter mana"><i style={{width:`${mp}%`}}/></div></div><div className="top-bar"><span>XP</span><div className="meter xp"><i style={{width:`${xpPercent}%`}}/></div></div><div className="top-bar" title={formatStamina(stamina)}><span>ST</span><div className="meter stamina"><i style={{width:`${sta}%`}}/></div></div></div><div className="pill gold"><i className="coin-dot"/>{gold.toLocaleString('pt-BR')}</div><div className="pill coin"><i className="crystal-dot"/>{coins}</div><button type="button" className={`pill objective-pill ${trackerVisible?'on':''}`} title={trackerVisible?'Ocultar painel de objetivo':`Abrir objetivo: ${trackerTitle}`} onClick={toggleTracker}>Objetivo: lvl {level+1} · {levelGoal}%</button><nav className="nav-icons">{visibleNav.map(item=><button key={item.id} data-tutorial={item.id} className={`iconbtn nav-${item.id} ${overlay===item.id?'on':''}`} onClick={()=>onOverlay(item.id)}><NavIcon id={item.id} tone={item.tone} badge={badges?.[item.id]}/><small>{item.label}</small></button>)}</nav><div className="top-right"><a className="btn" style={{color:'var(--ink)',textDecoration:'none'}} href="#wiki" target="_blank" rel="noopener noreferrer">Tutorial</a><button className={`flag ${locale==='pt'?'on':''}`} onClick={()=>setLocale('pt')}><img src={uiUrl('flags/bra')} alt="BR"/></button><button className={`flag ${locale==='en'?'on':''}`} onClick={()=>setLocale('en')}><img src={uiUrl('flags/en')} alt="US"/></button><button className="iconbtn mini" title={t('settings')} onClick={onSettings}>⚙</button><button className="iconbtn mini" onClick={onBack}>{t('logout')}</button></div></header>

  {trackerVisible&&<section className={`objective-tracker ${trackerMinimized?'is-minimized':''}`} aria-label="Rastreador de progressão"><header className="objective-tracker__head"><div className="objective-tracker__title"><span className="objective-tracker__kicker">Missão de progressão</span><strong>{trackerTitle}</strong></div><div className="objective-tracker__controls"><button type="button" className="objective-tracker__control" title={trackerMinimized?'Expandir':'Minimizar'} aria-label={trackerMinimized?'Expandir objetivo':'Minimizar objetivo'} onClick={toggleTrackerMinimized}>{trackerMinimized?'▣':'−'}</button><button type="button" className="objective-tracker__control" title="Ocultar" aria-label="Ocultar objetivo" onClick={hideTracker}>×</button></div></header>{!trackerMinimized&&<div className="objective-tracker__body"><div className="objective-tracker__level-line"><span>Nível atual: {level}</span><strong>{levelGoal}% para o nível {level+1}</strong></div><div className="objective-tracker__bar" aria-label={`Progresso ${levelGoal}%`}><i style={{width:`${levelGoal}%`}}/></div>{nextUnlockLevel!==undefined?<><p className="objective-tracker__goal">{nextUnlockLevel===level+1?<>Ao alcançar o <strong>nível {nextUnlockLevel}</strong>, você libera:</>:<>Meta: alcance o <strong>nível {nextUnlockLevel}</strong>. Faltam {nextUnlockLevel-level} níveis para liberar:</>}</p><div className="objective-tracker__unlock-list">{nextUnlocks.map(entry=>{const copy=UNLOCK_COPY[entry.item.id];return <article className="objective-unlock-card" key={entry.item.id}><div className="objective-unlock-card__icon"><NavIcon id={entry.item.id} tone={entry.item.tone}/></div><div><h4>{entry.item.label}<span>Nível {entry.level}</span></h4><p>{copy?.summary??'Novo recurso de progressão do personagem.'}</p><small><b>Função:</b> {copy?.purpose??'Expandir suas opções dentro do jogo.'}</small></div></article>})}</div>{laterUnlocks.length>0&&<div className="objective-tracker__later"><strong>Depois:</strong> {laterUnlocks.map((entry,index)=><span key={entry.item.id}>{index>0?' · ':''}{entry.item.label} no lvl {entry.level}</span>)}</div>}</>:<div className="objective-tracker__complete"><strong>Todos os sistemas principais deste rastreador já foram liberados.</strong><br/>Continue evoluindo para fortalecer o personagem, abrir hunts e avançar nos sistemas internos de progressão.</div>}</div>}</section>}

  {arenaHead&&createPortal(<button type="button" className="btn arena-city" data-tutorial="city" onClick={onCity}>Cidade</button>,arenaHead)}
  <nav className="mobile-main-nav"><button data-tutorial="city" onClick={onCity}><MobileMainIcon id="city"/><strong>Cidade</strong></button><button data-tutorial="hunts" onClick={openHunts}><MobileMainIcon id="hunts"/><strong>Hunts</strong></button><button onClick={onTraining}><MobileMainIcon id="training"/><strong>Treino</strong></button><button data-tutorial="mobile-menu" className={mobileMenu?'on':''} onClick={()=>setMobileMenu(v=>!v)}><MobileMainIcon id="menu"/><strong>Menu</strong></button></nav>
  {mobileMenu&&<div className="mobile-menu-backdrop" onClick={()=>setMobileMenu(false)}><section className="mobile-menu-sheet" onClick={e=>e.stopPropagation()}><header><h2>Menu</h2><button onClick={()=>setMobileMenu(false)}>×</button></header><div className="mobile-menu-scroll"><p className="lede" style={{margin:'0 0 10px'}}>Próximo objetivo: <strong>nível {level+1}</strong> · {levelGoal}% concluído.</p>{nextUnlockLevel!==undefined&&<p className="lede" style={{margin:'0 0 10px'}}>Próximo desbloqueio: <strong>{nextUnlocks.map(entry=>entry.item.label).join(', ')}</strong> no nível {nextUnlockLevel}.</p>}<h3>GERAL</h3><div className="mobile-menu-grid">{visibleNav.filter(x=>['helper','cyclopedia','rank','build'].includes(x.id)).map(item=><button key={item.id} data-tutorial={item.id} onClick={()=>openMobile(item.id)}><NavIcon id={item.id} tone={item.tone} badge={badges?.[item.id]}/><strong>{item.label}</strong></button>)}</div><h3>PROGRESSÃO</h3><div className="mobile-menu-grid">{visibleNav.filter(x=>['progressao','roleta','vip'].includes(x.id)).map(item=><button key={item.id} data-tutorial={item.id} onClick={()=>openMobile(item.id)}><NavIcon id={item.id} tone={item.tone}/><strong>{item.label}</strong></button>)}</div><h3>COMÉRCIO</h3><div className="mobile-menu-grid">{visibleNav.filter(x=>['market','loja','depot'].includes(x.id)).map(item=><button key={item.id} data-tutorial={item.id} onClick={()=>openMobile(item.id)}><NavIcon id={item.id} tone={item.tone}/><strong>{item.label}</strong></button>)}</div><h3>SOCIAL</h3><div className="mobile-menu-grid">{visibleNav.filter(x=>x.id==='guild').map(item=><button key={item.id} data-tutorial={item.id} onClick={()=>openMobile(item.id)}><NavIcon id={item.id} tone={item.tone}/><strong>{item.label}</strong></button>)}<button onClick={()=>{setMobileMenu(false);onSettings?.()}}><span className="mobile-menu-symbol">⚙</span><strong>{t('settings')}</strong></button></div><h3>CONTA</h3><div className="mobile-menu-grid"><button onClick={()=>setLocale('pt')}><span className="mobile-menu-symbol">🇧🇷</span><strong>Português</strong></button><button onClick={()=>setLocale('en')}><span className="mobile-menu-symbol">🇺🇸</span><strong>English</strong></button><button onClick={onBack}><span className="mobile-menu-symbol">↪</span><strong>Sair</strong></button></div></div></section></div>}
 </>
}