import { useMemo, useState } from 'react';
import { hunts, monsters, items, vocations, spellsCatalog, charms, bossEncounters, outfitsCatalog, mountsCatalog, stages } from '@tibia-idle/data';
import { GUILD_COST, partySlotPrices, SHOP, IMBUEMENTS, WHEEL_NODES } from '@tibia-idle/sim';
import './portal.css';

const GUIDES = [
  { title: 'Primeiros passos — tutorial', paragraphs: [
    '1. Abra Minha conta na página inicial, entre na sua conta ou registre-se. O painel mostra seus personagens, saldos e progresso sem iniciar o jogo.',
    '2. Crie um personagem e escolha a vocação. Knight luta próximo dos monstros; Paladin usa armas à distância; Sorcerer e Druid usam magia; Monk tem suas próprias habilidades de combate.',
    '3. Entre com o personagem. A Cidade é a Safe Zone: você está fora da caçada, pode organizar o equipamento, acessar o depósito e recuperar stamina.',
    '4. Abra Itens para conferir armas, armadura e mochila. Os itens precisam ser compatíveis com a classe, nível e slot do personagem.',
    '5. Abra o Helper e configure ataque, poções e cura. Confira os suprimentos antes de sair. As opções de fuga e falta de suprimentos ajudam a encerrar uma caçada perigosa.',
    '6. Abra Hunts e escolha um local liberado. O nível mínimo do conteúdo não pode superar o nível do principal da party. O desbloqueio acompanha o aumento do nível.',
    '7. Escolha a duração e inicie a caçada. Os suprimentos são preparados para a viagem e têm custo. Se a cave estiver cheia, seu personagem pode entrar na fila.',
    '8. O combate acontece automaticamente. A próxima onda surge inteira quando a anterior termina e a taxa de surgimento da cave permite. Só derrotar monstros gera a XP de combate.',
    '9. Para formar uma party, abra Config no painel Party. Adicione ou arraste seus personagens para Formação, escolha o Principal e salve. Arrastar para Principal não remove o personagem da formação.',
    '10. Use o status do membro no painel para ativá-lo na caçada do principal. Somente membros ativos na mesma caçada recebem a divisão de XP. Com três, cada um recebe um terço; sobras inteiras alternam entre os participantes.',
    '11. Acompanhe HP, mana, XP e stamina. O botão Cidade encerra as caçadas da formação e retorna à zona segura. Treino online é acessível no topo e na janela de caçadas.',
    '12. Venda loot, melhore o equipamento, consulte Bestiário, Prey e Progressão. Use Minha conta para acompanhar os personagens sem abrir o jogo. Volte à Wiki para comparar conteúdo e requisitos.',
  ] },
  { title: 'Conta, personagens e segurança', paragraphs: ['A conta reúne os personagens e suas permissões. Ouro, coins, equipamento e progresso são armazenados por personagem; os totais do painel somam esses saldos.', 'A seleção de personagens informa o limite da conta. Cada personagem tem vocação, aparência, nível, habilidades e inventários próprios. A administração está disponível somente para contas autorizadas pelo servidor.'] },
  { title: 'Cidade, stamina e descanso', paragraphs: ['Cidade é a Safe Zone, fora de uma hunt. A recuperação da stamina usa o tempo descansando, inclusive com a tela aberta e com consultas frequentes ao servidor.', 'O limite é 42 horas. Os primeiros 10 minutos contínuos de descanso são a espera inicial. Até 39 horas, cada 3 minutos de descanso recuperam 1 minuto de stamina; de 39 a 42 horas, cada 6 minutos recuperam 1 minuto. Frações de tempo são preservadas entre atualizações.', 'Ao voltar a caçar, o período contínuo de descanso é reiniciado. Stamina baixa reduz os benefícios da caçada; confira os indicadores antes de uma viagem longa.'] },
  { title: 'Caçadas, ondas e acesso por nível', paragraphs: ['O nível mínimo cadastrado da cave define o acesso. O principal nível 51 pode entrar em conteúdo de nível 51 ou inferior; nível 52 permanece bloqueado. Bosses, raids e eventos usam seu nível mínimo. Os companheiros usam a elegibilidade do principal.', 'Recomendação de combate e nível mínimo são conceitos diferentes: uma cave liberada ainda pode ser difícil para seu equipamento e suas habilidades. Monstros, taxas de XP, loot e vocações podem ser consultados no catálogo.', 'As ondas são completas; não há reposição contínua no meio de uma onda. O surgimento acumula crédito pela taxa configurada da caçada, limitado a uma onda. O dano alto não remove esse limite.'] },
  { title: 'Party, principal e experiência', paragraphs: ['A formação comporta até três personagens da mesma conta. Um personagem não pode pertencer a duas formações ao mesmo tempo. Salvar a formação também funciona na cidade; estar na formação não ativa automaticamente uma caçada.', 'A morte de um monstro gera um prêmio de XP que é dividido igualmente entre os participantes ativos na mesma hunt naquele momento. Inativos não recebem XP compartilhada. Consultar o membro ou o principal não duplica o prêmio. A divisão não exige níveis semelhantes.', 'Itens abre o equipamento e a mochila compartilhada. Aparência permite editar o personagem selecionado. O principal pode ser trocado pelos cards da formação.', 'Segundo slot: ' + partySlotPrices(1).gold.toLocaleString('pt-BR') + ' gold. Terceiro slot: ' + partySlotPrices(2).gold.toLocaleString('pt-BR') + ' gold. Os slots adicionais da party são desbloqueados somente com gold. Convites entre contas não estão disponíveis nesta formação.'] },
  { title: 'Combate, classes, Helper e suprimentos', paragraphs: ['A vocação define habilidades, equipamento e magias compatíveis. Nível, skills, magic level, arma, armadura, resistências, buffs e condições influenciam o combate.', 'O Helper organiza autoataque, prioridade de magias, cura, poções, runas, suporte e critérios de parada. Use limites de vida e mana adequados; as ações consomem recursos e respeitam cooldowns.', 'Os suprimentos incluem poções, munição e outros consumíveis configurados. O servidor calcula o pacote e o custo; se houver recursos no armazém, o reabastecimento pode aproveitá-los antes de comprar.'] },
  { title: 'Inventários, equipamentos e economia', paragraphs: ['Equipamento tem slots e restrições por classe e nível. Mochila, suprimentos, loot da caçada e depósito têm funções próprias. Confira a origem de um item ao equipar, usar, mover ou vender.', 'O loot depende dos monstros derrotados e seus sorteios. A tabela de cada monstro lista as entradas de loot da base. Ouro, preço de venda e preço de compra não são necessariamente iguais.', 'Mercado permite negociar com outros jogadores quando o item é negociável. A Loja reúne ofertas, serviços e consumíveis. Custos e requisitos exibidos são validados pelo servidor.'] },
  { title: 'Progressão, Bestiário, Charms e Prey', paragraphs: ['Nível aumenta com experiência. Habilidades de combate, magic level e treino têm progressões próprias. A tabela de estágios do catálogo mostra multiplicadores da base.', 'Derrotar espécies avança o Bestiário. Os estágios revelam informações e concedem progresso para charms. Charms podem ser vinculados conforme seus requisitos.', 'Prey usa slots, seleção de criaturas e bônus temporários de dano, defesa, experiência ou loot. Rerolls, wildcards, bloqueios e opções automáticas consomem os recursos indicados na interface.'] },
  { title: 'Treino online e offline', paragraphs: ['Treino online possui salas e alvos próprios, acessíveis ao lado de Cidade e na janela de conteúdo. O personagem precisa estar fora de uma caçada para treinar.', 'Armas de exercise possuem cargas e regras específicas. Treino de skills não equivale à XP compartilhada de matar monstros. O treino offline e a recuperação de stamina são processados conforme o tempo elegível do personagem.'] },
  { title: 'Bosses, raids, eventos e Bosstiário', paragraphs: ['Conteúdo especial é listado com nível mínimo, categoria, condições e cooldown. Sua disponibilidade é validada novamente no servidor, inclusive quando o personagem vem da fila.', 'Concluir encontros pode registrar mortes de boss, recompensas e cooldowns. Consulte os encontros no catálogo para níveis, criaturas, descrições e tempos configurados.'] },
  { title: 'Guilds e comunidade', paragraphs: ['Abra Guild no menu para criar, entrar, visualizar membros ou sair. Fundar uma guild custa ' + GUILD_COST.toLocaleString('pt-BR') + ' gold. O líder pode expulsar membros; se sair com outros membros presentes, a liderança é transferida.', 'Guild não é party: ela organiza a comunidade, enquanto a party organiza os participantes da caçada e a divisão de XP. Os canais de chat e o ranking permitem acompanhar a comunidade.'] },
  { title: 'Forja, imbuements e roda de habilidades', paragraphs: ['A forja usa recursos, slots e tiers de equipamento. Fusão, transferência e conversões seguem seus custos, compatibilidade e resultados definidos no jogo.', 'Imbuements oferecem bônus com duração e reagentes. Confira slots aceitos, tiers, custos e ingredientes no catálogo. Equipar um item não ignora as restrições de sua classe.', 'A roda de habilidades possui nós, limites de rank e pontos ligados ao progresso. A interface mostra pontos disponíveis e requisitos antes de aplicar uma melhoria.'] },
  { title: 'Bênçãos, morte e encerramento de hunts', paragraphs: ['Bênçãos influenciam as penalidades de morte. O botão de bênçãos do painel abre suas opções e preços. Não confunda bênçãos com invulnerabilidade.', 'A morte encerra a sessão e aplica as penalidades calculadas pelo servidor. Ao voltar ao templo, vida e mana são restauradas. Uma parada normal encerra a hunt e trata loot e suprimentos restantes conforme a política configurada.'] },
  { title: 'VIP, boosts, recompensas e aparência', paragraphs: ['VIP e boosts são temporários. A duração e os bônus dependem da oferta ou recompensa. Daily tem controle diário; códigos e ofertas exigem validação no servidor.', 'Outfits, cores, addons e montarias dependem de desbloqueios, compatibilidade e opções disponíveis. Aparência muda a apresentação do personagem e não concede automaticamente os atributos de um equipamento.', 'Roleta e outros sorteios usam custos e prêmios próprios. Consulte a interface antes de gastar coins; resultados aleatórios não são garantidos.'] },
  { title: 'Progresso offline e perguntas frequentes', paragraphs: ['Fechar o navegador não significa parar uma caçada ativa. O servidor simula o período elegível quando o personagem é consultado. O limite de recuperação é 8 horas para conta gratuita e 24 horas para VIP; períodos considerados offline usam 70% da eficiência normal de XP e loot.', 'Não recebi XP na party: confira se o membro está ativo, na mesma hunt e se algum monstro morreu. Equipamento e classe podem fazer personagens matarem em ritmos diferentes, mas a divisão do prêmio é igual entre os elegíveis.', 'Não recuperei stamina ainda: confira se está realmente fora da hunt, espere o atraso inicial e depois o tempo necessário para recuperar um minuto. O contador não sobe a cada segundo.', 'Não consigo entrar em conteúdo: confira nível mínimo do principal, slots da party, suprimentos, custo, cooldown e disponibilidade da cave. Consulte a mensagem do servidor.'] },
];

const CATALOGS = { 'Caçadas': hunts, 'Monstros': monsters, 'Itens': items, 'Vocações': vocations, 'Magias': spellsCatalog, 'Bosses e eventos': bossEncounters, 'Charms': charms, 'Outfits': outfitsCatalog, 'Montarias': mountsCatalog, 'Imbuements': IMBUEMENTS, 'Roda de habilidades': WHEEL_NODES, 'Loja': SHOP, 'Estágios': [stages] };
const LABELS: Record<string, string> = { id: 'Identificação', name: 'Nome', description: 'Descrição', level: 'Nível mínimo', minLevel: 'Nível mínimo', levelRequired: 'Nível exigido', location: 'Local', monsters: 'Monstros', expectedXpPerHour: 'XP base por hora', expectedLootPerHour: 'Loot previsto por hora', premium: 'Premium', partySizes: 'Formações', health: 'Vida', experience: 'Experiência', speed: 'Velocidade', armor: 'Armadura', defense: 'Defesa', attack: 'Ataque', loot: 'Loot', chance: 'Chance (escala da base)', maxCount: 'Quantidade máxima', itemId: 'Item', itemName: 'Nome do item', attacks: 'Ataques', elements: 'Elementos', immunities: 'Imunidades', mana: 'Mana', words: 'Palavras', cooldown: 'Cooldown', vocations: 'Vocações', sellPrice: 'Preço de venda', buyPrice: 'Preço de compra', weight: 'Peso (base)', slot: 'Slot', type: 'Tipo', duration: 'Duração (base)', charges: 'Cargas', cost: 'Custo', tiers: 'Tiers', slots: 'Slots', range: 'Alcance', bonuses: 'Bônus', bestiary: 'Bestiário', category: 'Categoria', unlocked: 'Desbloqueado', from: 'Origem', price: 'Preço', currency: 'Moeda' };
function DetailValue({ value, depth = 0 }: { value: unknown; depth?: number }) {
  if (value === null || value === undefined) return <span>—</span>;
  if (typeof value === 'boolean') return <span>{value ? 'Sim' : 'Não'}</span>;
  if (Array.isArray(value)) return value.length ? <ul>{value.map((entry, index) => <li key={index}><DetailValue value={entry} depth={depth + 1} /></li>)}</ul> : <span>Sem registros</span>;
  if (typeof value === 'object') return <dl className="wiki-detail">{Object.entries(value).filter(([key]) => !['clientId', 'hasSprite', 'sprites', 'flags'].includes(key)).map(([key, entry]) => <div key={key}><dt>{LABELS[key] ?? key.replace(/([A-Z])/g, ' $1')}</dt><dd><DetailValue value={entry} depth={depth + 1} /></dd></div>)}</dl>;
  return <span>{typeof value === 'number' ? value.toLocaleString('pt-BR') : String(value)}</span>;
}

export function WikiScreen({ onHome, onPlay }: { onHome: () => void; onPlay: () => void }) {
  const [section, setSection] = useState('Guia e tutorial');
  const [query, setQuery] = useState('');
  const [page, setPage] = useState(0);
  const catalog = CATALOGS[section as keyof typeof CATALOGS];
  const entries = useMemo(() => {
    const all = catalog ? (Array.isArray(catalog) ? catalog : Object.values(catalog)) as unknown as Record<string, unknown>[] : [];
    return all.filter((entry) => String(entry.name ?? entry.id ?? section).toLowerCase().includes(query.toLowerCase()));
  }, [catalog, query, section]);
  const guides = GUIDES.filter((guide) => [guide.title, ...guide.paragraphs].join(' ').toLowerCase().includes(query.toLowerCase()));
  return <main className="portal-page"><header className="portal-nav"><button onClick={onHome}>← Início</button><strong>WIKI · IDLE KNOCK TIBIA</strong><button onClick={onPlay}>Jogar</button></header><div className="portal-content">
    <div className="portal-heading"><span>MANUAL DO AVENTUREIRO</span><h1>Wiki do jogo</h1><p>Tutorial, regras e catálogo completo dos registros disponíveis nesta versão do jogo.</p></div>
    <div className="wiki-layout"><aside className="wiki-sidebar">{['Guia e tutorial', ...Object.keys(CATALOGS)].map((label) => <button className={section === label ? 'on' : ''} key={label} onClick={() => { setSection(label); setQuery(''); setPage(0); }}>{label}</button>)}</aside>
      <section className="wiki-main"><h2>{section}</h2><input aria-label="Buscar na Wiki" placeholder="Buscar nesta seção…" value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} />
        {section === 'Guia e tutorial' ? <>{guides.map((guide, index) => <details className="wiki-guide" key={guide.title} open={index === 0 || !!query}><summary>{guide.title}</summary>{guide.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</details>)}{!guides.length && <p>Nenhum tópico encontrado.</p>}</>
          : <><p>{entries.length.toLocaleString('pt-BR')} registros. Abra um registro para consultar atributos, requisitos e detalhes da base. Unidades não normalizadas estão identificadas como valores da base.</p>{entries.slice(page * 30, page * 30 + 30).map((entry, index) => <details className="wiki-guide" key={String(entry.id ?? entry.name ?? index)}><summary>{String(entry.name ?? entry.id ?? 'Tabela de estágios')} {entry.level !== undefined && <small>· nível {String(entry.level)}</small>}</summary><DetailValue value={entry} /></details>)}<div className="wiki-pagination"><button disabled={page === 0} onClick={() => setPage(page - 1)}>Anterior</button><span>Página {page + 1} de {Math.max(1, Math.ceil(entries.length / 30))}</span><button disabled={(page + 1) * 30 >= entries.length} onClick={() => setPage(page + 1)}>Próxima</button></div></>}
      </section>
    </div>
  </div></main>;
}
