const fs = require('fs');
const path = require('path');
const { chromium } = require(path.join(process.env.TEMP, 'idle-party-browser-check/node_modules/playwright'));
const fixture = JSON.parse(fs.readFileSync(path.join(process.env.TEMP, 'idle-party-browser-check/fixture.json')));
(async () => {
  const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(token => localStorage.setItem('tibia-idle.token', token), fixture.token);
  await page.request.put('http://127.0.0.1:3018/api/characters/' + fixture.ids[1] + '/party', { headers: { authorization: 'Bearer ' + fixture.token }, data: { memberIds: fixture.ids.slice(0,2), primaryId: fixture.ids[0] } });
  page.on('response', async response => { if(response.url().includes('party-items')) console.log('ITEMS RESPONSE',response.status(),(await response.text()).slice(0,180)); });
  await page.goto('http://127.0.0.1:5188');
  await page.getByRole('button', { name: 'WIKI', exact: true }).click();
  await page.getByRole('heading', { name: 'Wiki do jogo' }).waitFor();
  await page.getByRole('button', { name: 'Monstros', exact: true }).click();
  await page.getByRole('textbox', { name: 'Buscar na Wiki' }).fill('rotworm');
  if (!(await page.locator('.wiki-guide').count())) throw new Error('Wiki monster search returned no data');
  await page.getByRole('button', { name: '← Início' }).click();
  await page.getByRole('button', { name: 'MINHA CONTA', exact: true }).first().click();
  await page.getByRole('heading', { name: 'gbllima', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Administração', exact: true }).click();
  await page.getByRole('heading', { name: 'Editar ouro' }).waitFor();
  await page.getByRole('button', { name: 'Minha conta', exact: true }).click();
  await page.getByRole('button', { name: 'Entrar com este personagem' }).first().click();
  await page.getByRole('button', { name: 'Config', exact: true }).waitFor();
  fs.mkdirSync('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/game-party.png' });
  await page.getByRole('button', { name: 'Config', exact: true }).click();
  await page.getByRole('heading', { name: 'Gerenciar party' }).waitFor();
  await page.screenshot({ path: 'artifacts/party-config.png' });
  await page.getByRole('button', { name: 'Tornar principal', exact: true }).first().click();
  await page.getByRole('button', { name: 'Salvar alterações' }).click();
  await page.locator('.party-manager').waitFor({ state: 'detached' });
  const response = await page.request.get('http://127.0.0.1:3018/api/characters/' + fixture.ids[1], { headers: { authorization: 'Bearer ' + fixture.token } });
  const updated = (await response.json()).character;
  if (updated.partyMemberIds[0] !== fixture.ids[1] || updated.partyMemberIds.length !== 2) throw new Error('Leadership change was not persisted');
  await page.getByRole('button', { name: 'Itens', exact: true }).first().click();
  await page.locator('.modal').last().waitFor({timeout:5000}).catch(async e => { await page.screenshot({path:'artifacts/browser-error.png'}); console.log(await page.locator('.party-inline-error').allTextContents()); throw e; });
  await page.screenshot({ path: 'artifacts/party-items.png' });
  await page.getByRole('button', { name: 'Fechar', exact: true }).last().click();
  await page.getByRole('button', { name: 'Aparência', exact: true }).first().click();
  await page.locator('.modal').last().waitFor();
  await page.screenshot({ path: 'artifacts/party-appearance.png' });
  await page.getByRole('button', { name: 'Fechar', exact: true }).last().click();
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('PASS: Wiki search, account and admin panels, party configuration, saved leadership, items and appearance; no browser errors.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
